styleguide: sourcelevel/linters
engines:
  reek:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
    channel: latest
  brakeman:
    enabled: true
  sass-lint:
    enabled: true
  duplication:
    config:
      languages:
        - ruby
    enabled: true
  remark-lint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
  - bin
  - config
  - db
  - public
  - spec
  - tmp
  - vendor
